version: '3.8'
services:
  backend:
    build: ./itog/backend
    secrets:
      - firebase_creds
    networks:
      - app-network

  frontend:
    build: ./itog/frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  admin:
    build: ./adminzakaz
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

secrets:
  firebase_creds:
    file: ./secrets/zakazedi-3c538-firebase-adminsdk-xe6q5-5f2a0a4a08.json